Updated config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -176,7 +176,46 @@ jobs:
             root: ~/
             paths:
               - projects/backend
-
+  run-migrations:
+    docker:
+      - image: circleci/node:13.8.0
+    steps:
+      - checkout
+      - attach_workspace:
+          at: ~/
+      - restore_cache:
+          keys: [backend-build]
+      - run:
+          name: awscli install
+          command: |
+            sudo apt-get -y -qq update
+            sudo apt-get -y -qq install python3
+            sudo apt-get -qq install awscli
+      - run:
+          name: Run migrations
+          command: |
+            cd backend
+            npm install
+            npm run migrations:revert
+            if [ $? -eq 0 ]; then echo "install success"; fi
+            echo "MIGRATIONS STARTED" > migrations_dump.txt
+            npm run migrations >> migrations_dump.txt
+            cat migrations_dump.txt
+      - run:
+          name: Send migration results to kvdb
+          command: |
+            if grep -q "successfully"  ~/project/backend/migrations_dump.txt
+            then
+              echo "success"
+            else echo "fail"
+            fi
+            cd backend
+            if grep "has been executed successfully" migrations_dump.txt
+            then
+              curl -k https://kvdb.io/2wKc5aL4zJjVve6Y6qjabv/migration_${CIRCLE_WORKFLOW_ID:0:7} -d '1'
+            else curl -k https://kvdb.io/2wKc5aL4zJjVve6Y6qjabv/migration_${CIRCLE_WORKFLOW_ID:0:7} -d '2'
+            fi
+            
 workflows:
   default:
     jobs:
